name: checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '6.0'

      - name: Build a universal binary
        run: swift build --configuration release --arch arm64 --arch x86_64

      - name: Perform a test run
        run: 'export BIN=.build/apple/Products/Release/ql && test -x $BIN && test "$($BIN)" = "Usage: ql [--title <title>] <path>"'

  vint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install --upgrade pip && pip install vim-vint

      - name: Run vint
        run: vint .
